runtime: python310  

instance_class: F2  

entrypoint: gunicorn -b :$PORT customer_orders.wsgi  

env_variables:
  DJANGO_SETTINGS_MODULE: customer_orders.settings  
  SECRET_KEY: ${SECRET_KEY}  

handlers:
  - url: /static
    static_dir: static/  

  - url: /.*
    script: auto  
