name: Deploy to GAE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r backend/requirements.txt  # Updated path

    - name: Run tests
      run: |
        python3 backend/manage.py test  # Ensure you use the correct path to manage.py

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --quiet
