name: Deploy to GAE

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

    thon
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.14'

   
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r backend/requirements.txt

   
      - name: Run tests
        run: |
          python3 backend/manage.py test

    
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

     
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      
      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy backend/app.yaml --quiet
