name: Deploy to GAE

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14  

    - name: Install dependencies
      run: |
        cd backend  
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd backend 
        python manage.py test

    - name: Deploy to Google App Engine
      run: |
        cd backend  
        gcloud app deploy --quiet
